### ISSUE TITLE
Rename quicklisp-meta to avoid confusion with quicklisp project

### ISSUE THREAD

**Issue by ryukinix** [commonlispbr/quicklisp-meta#9]
quicklisp-meta it's not oficially developed by xach (the original author of quicklisp). For that reason we need to think in a better and distinctive name about our software.

Our software proposal it's to make easy load systems that is defined in another dists. So this project currently tracks a collection of dists to be used as catalog and load a system from them.

**Comment by ryukinix** [comment]
# Discarted ideas

+ ~quickdist~ (already used, check this: https://ultralisp.org/projects/ultralisp/quickdist)
+ ~lispdim~ (LISP + RAPIDIM, doesn't makes much sense)
+ ~quickmeta~ (doesn't have any particular meaning about what the software does)
+ ~fedelisp~ (federation lisp, has a bad reading for portuguese speakers, means smells like shit)
+ ~quirklisp~ (fun, but depreciative)
+ ~quickielisp~ (misleading with quicklisp, doesn't have a good abreviation, too similar to quicklisp)
+ ~happylisp~ (seriously?)
+ ~quickerlisp~ (NO)

# Potential candidates

+ quicksys

**Comment by ryukinix** [comment]
If `quicksys` is chosen, we need to add the suffix `dist` to `install` and `uninstall`. Like this:

```
(qs:install-dist :bodge)
(qs:quickload :trivial-gamekit)
(qs:uinstall-dist :bodge)
```

**Comment by luksamuk** [comment]
I `+1` quicksys, under the proposition that, while the project is built under the premise of handling many dists, it is ultimately a tool for ensuring that you can load a system, regardless of dist.

Fedelisp really doesn't look good in Portuguese, but it seemed to me as a name for something truly federated, in the sense that we'd have to have a server-software which people can run on machines hosting dists, and a client-software which is responsible for system loading and discovery. Interesting, but not really the scope of the project. Would look fine on modern Lisp Machines running CL, though.

**Comment by ryukinix** [comment]
I think we should rewrite the documentation to emphasize the feature about installing system from different distributions. The current README.md give more attention to install/uninstall multiple dists from easy nicknames.

**Comment by luksamuk** [comment]
> The current README.md give more attention to install/uninstall multiple dists from easy nicknames.

True. I would suggest doing that prior to renaming the project, just for consistency.
